categories:
 - Transcriptomics
 - RNA
 - Sequence Analysis
description: "PySCENIC scripts based on usage at https://pyscenic.readthedocs.io/"
long_description: |
        pySCENIC is a lightning-fast python implementation of the SCENIC pipeline (Single-Cell rEgulatory Network Inference and Clustering) 
        which enables biologists to infer transcription factors, gene regulatory networks and cell types from single-cell RNA-seq data.
name: suite_pyscenic
owner: ebi-gxa
remote_repository_url: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the pySCENIC tool suite: {{ tool_name }}"
suite:
  name: "suite_pyscenic"
  description: "PySCENIC scripts based on usage at https://pyscenic.readthedocs.io/"
  long_description: |
    pySCENIC is a lightning-fast python implementation of the SCENIC pipeline (Single-Cell rEgulatory Network Inference and Clustering) 
    which enables biologists to infer transcription factors, gene regulatory networks and cell types from single-cell RNA-seq data.
