FROM pcm32/galaxy-init:v18.01

MAINTAINER EBI Expression Atlas Team <expression-atlas-team@ebi.ac.uk>

LABEL Description="Galaxy 18.01 - SC Tertiary Analysis"
LABEL software="Galaxy Init"
LABEL software.version="18.01"
LABEL version="1.7"

# RUN wget -O ephemeris.tar https://api.github.com/repos/galaxyproject/ephemeris/tarball/eeee87a57379b8b639b06c2a50038ef449c28d73 && \
#     tar -xf ephemeris.tar && rm ephemeris.tar && \
#     virtualenv venv-workflow && \
#     /bin/bash -c "source venv-workflow/bin/activate && \
#                   pip install 'pip>=8.1' && \
#                   pip install ./galaxyproject-ephemeris-eeee87a \
#                       --index-url https://pypi.python.org/simple && \
#                   pip install urllib3[secure] && \
#                   deactivate && \
#                   virtualenv --relocatable venv-workflow"

COPY config/job_conf.xml config/job_conf.xml
COPY config/tool_conf.xml config/tool_conf.xml
COPY config/sanitize_whitelist.txt config/sanitize_whitelist.txt
COPY tools/tertiary-analysis tools/tertiary-analysis

# Reqs/limits
COPY config/job_resource_params_conf.xml config/job_resource_params_conf.xml
COPY config/phenomenal_tools2container.yaml config/phenomenal_tools2container.yaml
COPY rules/k8s_destinations.py /galaxy-central/lib/galaxy/jobs/rules/k8s_destination.py

# Galaxy tours which guide users through the subsequent steps in an analysis
# COPY config/plugins/tours/*.yaml config/plugins/tours/

COPY html/Atlas_logo.png welcome/welcome_Atlas_logo.png
COPY html/welcome.html welcome/welcome.html

# COPY workflows workflows_to_load
# COPY post-start-actions.sh post-start-actions.sh
# RUN chmod u+x post-start-actions.sh
