categories:
 - Transcriptomics
description: "decoupler - Ensemble of methods to infer biological activities"
long_description: |
    decoupler is a package containing different statistical methods to extract biological
    activities from omics data within a unified framework. It allows to flexibly test any
    method with any prior knowledge resource and incorporates methods that take into account
    the sign and weight. It can be used with any omic, as long as its features can be linked
    to a biological process based on prior knowledge.
name: suite_decoupler
owner: ebi-gxa
remote_repository_url: https://github.com/ebi-gene-expression-group/container-galaxy-sc-tertiary/
homepage_url: https://decoupler-py.readthedocs.io/en/latest/
type: unrestricted
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "Wrapper for the decoupler tool suite: {{ tool_name }}"
suite:
  name: "suite_decoupler"
  description: "decoupler - Ensemble of methods to infer biological activities"
  long_description: |
    decoupler is a package containing different statistical methods to extract biological
    activities from omics data within a unified framework. It allows to flexibly test any
    method with any prior knowledge resource and incorporates methods that take into account
    the sign and weight. It can be used with any omic, as long as its features can be linked
    to a biological process based on prior knowledge.  
